### PR TITLE
Make CommandHandlerPass using the real merged config

### LINKED ISSUE #80: Default bus setup seems broken ?
Hello guys,

it looks we broke something in latest release.

Default bus is no longer setup if no configuration is defined.

Here is the Integration test that should pass:
```php
    public function testHandleCommandOnDefaultBus()
    {
        // We use default config
        $this->registerService('tactician.test.handler', \League\Tactician\Bundle\Tests\EchoTextHandler::class, [
            ['name' => 'tactician.handler', 'command' => 'League\Tactician\Bundle\Tests\EchoText'],
        ]);

        $this->expectOutputString('Hello world');
        $this->handleCommand('default', \League\Tactician\Bundle\Tests\EchoText::class, ['Hello world']);
    }
``` 

and it fails with stack trace
```
League\Tactician\Bundle\DependencyInjection\InvalidCommandBusId: Could not find a command bus with id 'default'. Valid buses are: 

/home/tyx/www/tactician-bundle/src/DependencyInjection/InvalidCommandBusId.php:10
/home/tyx/www/tactician-bundle/src/DependencyInjection/Compiler/BusBuilder/BusBuilders.php:61
/home/tyx/www/tactician-bundle/src/DependencyInjection/Compiler/BusBuilder/BusBuilders.php:29
/home/tyx/www/tactician-bundle/src/DependencyInjection/Compiler/BusBuilder/BusBuildersFromConfig.php:25
/home/tyx/www/tactician-bundle/src/DependencyInjection/Compiler/CommandHandlerPass.php:27
/home/tyx/www/tactician-bundle/vendor/symfony/dependency-injection/Compiler/Compiler.php:141
/home/tyx/www/tactician-bundle/vendor/symfony/dependency-injection/ContainerBuilder.php:757
/home/tyx/www/tactician-bundle/vendor/symfony/http-kernel/Kernel.php:624
/home/tyx/www/tactician-bundle/vendor/symfony/http-kernel/Kernel.php:137
/home/tyx/www/tactician-bundle/tests/Integration/IntegrationTest.php:64
/home/tyx/www/tactician-bundle/tests/Integration/BasicCommandAndBusMappingTest.php:20
```

I guess it is because of [getExtensionConfig](https://github.com/thephpleague/tactician-bundle/blob/2ca59ad65f8eb4e02eca29c27ed9e99e03ba97b6/src/DependencyInjection/Compiler/CommandHandlerPass.php#L27) that does not merge extension config with default config but I have no idea how to fix that.

I'm ready to make a PR if anyone else have an idea !

edit: Here is a detailled issue with this behavior (expected, not a bug) : https://github.com/symfony/symfony/issues/19149

### PR DESCRIPTION
**Pull request by tyx**
**Problem**
Because `container->getExtensionConfig()` does not return merged config.

**Solution**
Use a temporary dic parameter to transport the merged config to the CommandHandlerPass.

Fix #80

### CODE REVIEW

File: src/DependencyInjection/Compiler/CommandHandlerPass.php [hunk 1]
```diff
@@ -47,4 +49,12 @@ public function process(ContainerBuilder $container)
             $container->getDefinition('tactician.command.debug')->addArgument($mappings);
         }
     }
+
+    private function readAndForgetParameter(ContainerBuilder $container, $parameter)
```
Comment (shouze) [inline src/DependencyInjection/Compiler/CommandHandlerPass.php]: `s/$parameter/$parameterName/`?

**Comment by rosstuck** [comment]
Thanks for the fix! I'll tag a 1.1.1 for this after looking at the other PRs.

I do feel this is a weakness in Symfony's setup but as the least bad solution it works. :) (That's no disrespect to you @tyx, you rock for picking this up!)
